### ISSUE TITLE
[FEATURE] Universal support

### ISSUE THREAD

**Issue by fatters** [ng-web-apis/intersection-observer#11]
# 🚀 Feature request

### Is your feature request related to a problem?

Apologies if I'm misuing this, I will provide a sample project to show you how I'm using it.

When running npm run build:ssr and then npm run serve:ssr, we get the error:

`ReferenceError: IntersectionObserver is not defined`. And the Universal library doesn't provide a token for this.

### Describe the solution you'd like

A fallback for SSR to allow page load with a default 'not in viewport' value or something until our scripts load.

### Describe alternatives you've considered

I have tried both the directive way the service way. And have tried wrapping inner components with an isPlatformBrowser check which does allow npm run serve:ssr to run, but then fails to load the page.

### Additional context

I have provided a bare bones project [here](https://github.com/fatters/io-ssr) to show you what I mean.

```
npm install
npm run build:ssr
npm run serve:ssr
```

Error should appear: 
```!function(e,a){for(var i in a)e[i]=a[i]}(exports,function(modules){var installedModules={};function __webpack_require__(moduleId){if(installedModules[moduleId])return installedModules[moduleId].exports;var module=installedModules[moduleId]={i:moduleId,l:!1,exports:{}};return modules[moduleId].call(module.exports,module,module.exports,__webpack_require__),module.l=!0,module.exports}return __webpack_require__.m=modules,__webpack_require__.c=installedModules,__webpack_require__.d=function(exports,name,getter){__webpack_require__.o(exports,name)||Object.defineProperty(exports,name,{enumerable:!0,get:getter})},__webpack_require__.r=function(exports){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(exports,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(exports,"__esModule",{value:!0})},__webpack_require__.t=function(value,mode){if(1&mode&&(value=__webpack_require__(value)),8&mode)return value;if(4&mode&&"object"==typeo

ReferenceError: IntersectionObserver is not defined
```

**Comment by MarsiBarsi** [comment]
Hi! Thank you for your issue and interest in our library! We'll think about it and try to find a better solution

**Comment by waterplea** [comment]
Hello @fatters 
We decided to add mocks to native classes to our Universal package:
https://github.com/ng-web-apis/universal

Please take a look. Basically, you can add `@ng-web-apis/universal: 1.9.1` and add following line to your `server.ts`:

```js
import '@ng-web-apis/universal/mocks';
```

At the moment it mocks classes for IntersectionObserver, MutationObserver and Web Audio API so our packages can be easily used in SSR. Feel free to comment or reopen this issue if you have any questions.
