### ISSUE TITLE
Angular 9 supported?

### ISSUE THREAD

**Issue by aguerere** [ng-web-apis/intersection-observer#13]
I'm wondering if this is supposed to work with Angular 9? I'm trying to use the waIntersectionObserver directive directly from the examples available here and its not triggering the waIntersectionObservee for me.
I'm on Angular 9.1.11 . Thank you.

**Comment by waterplea** [comment]
Hi there. Yes, it works for Angular 9. Can you make a StackBlitz reproduction?

**Comment by aguerere** [comment]
@waterplea here is a sample in StackBlitz, behavior is the same for me. https://stackblitz.com/edit/angular-9-1-11-intersection-observer?file=src%2Fapp%2Fapp.component.html
Thanks

**Comment by aguerere** [comment]
Hi @waterplea I was forgetting to import the IntersectionObserverModule in the app.module.ts .
I know this is customary for most Angular libraries, but you guys should mention it in the readme to save newbies from despair. Thank you!

**Comment by waterplea** [comment]
Done. Thank you for highlighting this!
