### ISSUE TITLE
[FEATURE] add docs on testing

### ISSUE THREAD

**Issue by bboydflo** [ng-web-apis/intersection-observer#14]
First of all, thanks for this library.

# 🚀 Feature request

### Is your feature request related to a problem? YES

I have added this library to my angular project and have a bunch of tests that now fail with something like this

```sh
FAIL src/app/noc/pages/asset-overview/asset-overview.component.spec.ts
  ● Test suite failed to run

    ReferenceError: IntersectionObserver is not defined

      3 | import { ActivatedRoute } from '@angular/router';
      4 | import { RouterTestingModule } from '@angular/router/testing';
    > 5 | import { IntersectionObserveeDirective, IntersectionObserveeService, IntersectionObserverModule, IntersectionObserverService, IntersectionRootDirective } from '@ng-web-apis/intersection-observer';
        | ^
      6 | import {
      7 |     createComponentFactory,
      8 |     Spectator,

      at node_modules/@ng-web-apis/intersection-observer/bundles/@ng-web-apis/intersection-observer/directives/intersection-observer.directive.ts:17:52
      at node_modules/@ng-web-apis/intersection-observer/bundles/ng-web-apis-intersection-observer.umd.js:2:68
      at Object.<anonymous> (node_modules/@ng-web-apis/intersection-observer/bundles/ng-web-apis-intersection-observer.umd.js:5:2)
      at Object.<anonymous> (src/app/noc/pages/asset-overview/asset-overview.component.spec.ts:5:1)
```

### Describe the solution you'd like

I would like to have a basic example of how to write a test for a component that used this lib.

### Describe alternatives you've considered

N/A

**Comment by waterplea** [comment]
Hello, @bboydflo. Thank you for kind words. You probably use Jest for testing, right? It doesn't have `IntersectionObserver` class because it's an emulation of browser ran in node.js. So you would need to add global class to testing polyfills that implements an interface. You can use `mocks` from this package:
https://github.com/ng-web-apis/universal#mocks

It's a good idea to add this to the README, if you get this working for you and will be willing to contribute, a PR with a short instruction is very welcome.

**Comment by bboydflo** [comment]
@waterplea Thanks for a quick answer. Yes, I use jest. I will try it and make a PR if everything goes well

**Comment by bboydflo** [comment]
@waterplea adding this line `import '@ng-web-apis/universal/mocks';` to my jest `setup.ts` works! is there a way to only import mocks only for intersection observer though?

will make a PR to improve the docs soon

**Comment by waterplea** [comment]
If you look in that file it's pretty simple. You only need it for server side so it doesn't matter if it adds more than you need — this code does not get into bundle, it is only used on server or in tests. It doesn't make sense to import anything selectively.

**Comment by bboydflo** [comment]
yes, it makes sense and it's a lot cleaner. I am currently fighting with some tests and I just thought I should include stuff step by step. But as you said, it should not break anything.
